# Generated by Django 5.1.1 on 2024-10-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoshield', '0008_user_descripcion_user_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='antecedente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
